[2025-01-28T02:21:53.163+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T02:21:53.192+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa1_dag.teste1 manual__2025-01-28T02:18:39.971264+00:00 [queued]>
[2025-01-28T02:21:53.205+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa1_dag.teste1 manual__2025-01-28T02:18:39.971264+00:00 [queued]>
[2025-01-28T02:21:53.206+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-28T02:21:53.233+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): teste1> on 2025-01-28 02:18:39.971264+00:00
[2025-01-28T02:21:53.244+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=247) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-28T02:21:53.247+0000] {standard_task_runner.py:72} INFO - Started process 251 to run task
[2025-01-28T02:21:53.247+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa1_dag', 'teste1', 'manual__2025-01-28T02:18:39.971264+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/etapa1_dag.py', '--cfg-path', '/tmp/tmpir5hmxgo']
[2025-01-28T02:21:53.249+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask teste1
[2025-01-28T02:21:53.316+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa1_dag.teste1 manual__2025-01-28T02:18:39.971264+00:00 [running]> on host 90d9eb5798dc
[2025-01-28T02:21:53.430+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa1_dag' AIRFLOW_CTX_TASK_ID='teste1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T02:18:39.971264+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T02:18:39.971264+00:00'
[2025-01-28T02:21:53.432+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-28T02:21:53.433+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-28T02:21:53.433+0000] {logging_mixin.py:190} INFO - Current task name:teste1 state:running start_date:2025-01-28 02:21:53.193370+00:00
[2025-01-28T02:21:53.434+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag and current dag run status:running
[2025-01-28T02:21:53.434+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T02:21:53.449+0000] {python.py:240} INFO - Done. Returned value was: 2155
[2025-01-28T02:21:53.477+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T02:21:53.478+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa1_dag, task_id=teste1, run_id=manual__2025-01-28T02:18:39.971264+00:00, execution_date=20250128T021839, start_date=20250128T022153, end_date=20250128T022153
[2025-01-28T02:21:53.491+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-28T02:21:53.492+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-28T02:21:53.493+0000] {logging_mixin.py:190} INFO - Dag name:etapa1_dag queued_at:2025-01-28 02:21:47.890832+00:00
[2025-01-28T02:21:53.493+0000] {logging_mixin.py:190} INFO - Task hostname:90d9eb5798dc operator:PythonOperator
[2025-01-28T02:21:53.544+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T02:21:53.573+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-28T02:21:53.578+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
