[2025-01-30T04:15:04.483+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T04:15:04.508+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa2_dag.copia manual__2025-01-30T03:32:35.404173+00:00 [queued]>
[2025-01-30T04:15:04.520+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa2_dag.copia manual__2025-01-30T03:32:35.404173+00:00 [queued]>
[2025-01-30T04:15:04.521+0000] {taskinstance.py:2866} INFO - Starting attempt 6 of 6
[2025-01-30T04:15:04.680+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): copia> on 2025-01-30 03:32:35.404173+00:00
[2025-01-30T04:15:04.689+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=905) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T04:15:04.690+0000] {standard_task_runner.py:72} INFO - Started process 907 to run task
[2025-01-30T04:15:04.691+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa2_dag', 'copia', 'manual__2025-01-30T03:32:35.404173+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/etapa2_dag.py', '--cfg-path', '/tmp/tmp2__564eg']
[2025-01-30T04:15:04.692+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask copia
[2025-01-30T04:15:04.742+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa2_dag.copia manual__2025-01-30T03:32:35.404173+00:00 [running]> on host eed2ce10479b
[2025-01-30T04:15:04.854+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa2_dag' AIRFLOW_CTX_TASK_ID='copia' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T03:32:35.404173+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T03:32:35.404173+00:00'
[2025-01-30T04:15:04.855+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T04:15:04.856+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T04:15:04.857+0000] {logging_mixin.py:190} INFO - Current task name:copia state:running start_date:2025-01-30 04:15:04.508944+00:00
[2025-01-30T04:15:04.857+0000] {logging_mixin.py:190} INFO - Dag name:etapa2_dag and current dag run status:running
[2025-01-30T04:15:04.858+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T04:15:04.960+0000] {python.py:240} INFO - Done. Returned value was: False
[2025-01-30T04:15:04.994+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T04:15:04.995+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa2_dag, task_id=copia, run_id=manual__2025-01-30T03:32:35.404173+00:00, execution_date=20250130T033235, start_date=20250130T041504, end_date=20250130T041504
[2025-01-30T04:15:05.009+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T04:15:05.010+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T04:15:05.010+0000] {logging_mixin.py:190} INFO - Dag name:etapa2_dag queued_at:2025-01-30 04:15:02.308217+00:00
[2025-01-30T04:15:05.010+0000] {logging_mixin.py:190} INFO - Task hostname:eed2ce10479b operator:PythonOperator
[2025-01-30T04:15:05.026+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T04:15:05.052+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-30T04:15:05.057+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
