[2025-01-30T04:32:04.101+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T04:32:04.131+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etapa2_dag.copia manual__2025-01-30T03:32:35.404173+00:00 [queued]>
[2025-01-30T04:32:04.144+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etapa2_dag.copia manual__2025-01-30T03:32:35.404173+00:00 [queued]>
[2025-01-30T04:32:04.146+0000] {taskinstance.py:2866} INFO - Starting attempt 13 of 13
[2025-01-30T04:32:04.165+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): copia> on 2025-01-30 03:32:35.404173+00:00
[2025-01-30T04:32:04.174+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1274) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T04:32:04.176+0000] {standard_task_runner.py:72} INFO - Started process 1276 to run task
[2025-01-30T04:32:04.176+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etapa2_dag', 'copia', 'manual__2025-01-30T03:32:35.404173+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/etapa2_dag.py', '--cfg-path', '/tmp/tmpjmw9gxb9']
[2025-01-30T04:32:04.177+0000] {standard_task_runner.py:105} INFO - Job 50: Subtask copia
[2025-01-30T04:32:04.232+0000] {task_command.py:467} INFO - Running <TaskInstance: etapa2_dag.copia manual__2025-01-30T03:32:35.404173+00:00 [running]> on host eed2ce10479b
[2025-01-30T04:32:04.345+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etapa2_dag' AIRFLOW_CTX_TASK_ID='copia' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T03:32:35.404173+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T03:32:35.404173+00:00'
[2025-01-30T04:32:04.347+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T04:32:04.347+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T04:32:04.348+0000] {logging_mixin.py:190} INFO - Current task name:copia state:running start_date:2025-01-30 04:32:04.132148+00:00
[2025-01-30T04:32:04.349+0000] {logging_mixin.py:190} INFO - Dag name:etapa2_dag and current dag run status:running
[2025-01-30T04:32:04.349+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T04:32:04.392+0000] {logging_mixin.py:190} INFO - Table: categories -- parquetfile: /data/postgres/categories/2025-01-30/file.parquet
[2025-01-30T04:32:04.696+0000] {logging_mixin.py:190} INFO - Tabela categories não existe. Criando a tabela...
[2025-01-30T04:32:04.739+0000] {logging_mixin.py:190} INFO - Table: customers -- parquetfile: /data/postgres/customers/2025-01-30/file.parquet
[2025-01-30T04:32:04.760+0000] {logging_mixin.py:190} INFO - Tabela customers não existe. Criando a tabela...
[2025-01-30T04:32:04.772+0000] {logging_mixin.py:190} INFO - Erro ao atualizar ou criar tabela customers: column "none" does not exist
LINE 1: ...Sales Representative', 'Obere Str. 57', 'Berlin', None, '122...
                                                             ^
HINT:  Perhaps you meant to reference the column "customers.phone".
[2025-01-30T04:32:04.781+0000] {logging_mixin.py:190} INFO - Table: customer_customer_demo -- parquetfile: /data/postgres/customer_customer_demo/2025-01-30/file.parquet
[2025-01-30T04:32:04.794+0000] {logging_mixin.py:190} INFO - Tabela customer_customer_demo não existe. Criando a tabela...
[2025-01-30T04:32:04.815+0000] {logging_mixin.py:190} INFO - Table: customer_demographics -- parquetfile: /data/postgres/customer_demographics/2025-01-30/file.parquet
[2025-01-30T04:32:04.830+0000] {logging_mixin.py:190} INFO - Tabela customer_demographics não existe. Criando a tabela...
[2025-01-30T04:32:04.854+0000] {logging_mixin.py:190} INFO - Table: employees -- parquetfile: /data/postgres/employees/2025-01-30/file.parquet
[2025-01-30T04:32:04.871+0000] {logging_mixin.py:190} INFO - Tabela employees não existe. Criando a tabela...
[2025-01-30T04:32:04.888+0000] {logging_mixin.py:190} INFO - Erro ao atualizar ou criar tabela employees: column "nan" does not exist
LINE 1: ...rce, and the Pacific Rim Importers Association.', nan, 'http...
                                                             ^
[2025-01-30T04:32:04.900+0000] {logging_mixin.py:190} INFO - Table: employee_territories -- parquetfile: /data/postgres/employee_territories/2025-01-30/file.parquet
[2025-01-30T04:32:04.916+0000] {logging_mixin.py:190} INFO - Tabela employee_territories não existe. Criando a tabela...
[2025-01-30T04:32:05.028+0000] {logging_mixin.py:190} INFO - Table: orders -- parquetfile: /data/postgres/orders/2025-01-30/file.parquet
[2025-01-30T04:32:05.048+0000] {logging_mixin.py:190} INFO - Tabela orders não existe. Criando a tabela...
[2025-01-30T04:32:05.062+0000] {logging_mixin.py:190} INFO - Erro ao atualizar ou criar tabela orders: syntax error at or near "Abbaye"
LINE 1: ... 32.38, 'Vins et alcools Chevalier', '59 rue de l'Abbaye', '...
                                                             ^
[2025-01-30T04:32:05.074+0000] {logging_mixin.py:190} INFO - Table: products -- parquetfile: /data/postgres/products/2025-01-30/file.parquet
[2025-01-30T04:32:05.091+0000] {logging_mixin.py:190} INFO - Tabela products não existe. Criando a tabela...
[2025-01-30T04:32:05.114+0000] {logging_mixin.py:190} INFO - Erro ao atualizar ou criar tabela products: syntax error at or near "s"
LINE 1: ...order_level, discontinued) VALUES (4, 'Chef Anton's Cajun Se...
                                                             ^
[2025-01-30T04:32:05.126+0000] {logging_mixin.py:190} INFO - Table: region -- parquetfile: /data/postgres/region/2025-01-30/file.parquet
[2025-01-30T04:32:05.142+0000] {logging_mixin.py:190} INFO - Tabela region não existe. Criando a tabela...
[2025-01-30T04:32:05.169+0000] {logging_mixin.py:190} INFO - Table: shippers -- parquetfile: /data/postgres/shippers/2025-01-30/file.parquet
[2025-01-30T04:32:05.182+0000] {logging_mixin.py:190} INFO - Tabela shippers não existe. Criando a tabela...
[2025-01-30T04:32:05.215+0000] {logging_mixin.py:190} INFO - Table: suppliers -- parquetfile: /data/postgres/suppliers/2025-01-30/file.parquet
[2025-01-30T04:32:05.233+0000] {logging_mixin.py:190} INFO - Tabela suppliers não existe. Criando a tabela...
[2025-01-30T04:32:05.246+0000] {logging_mixin.py:190} INFO - Erro ao atualizar ou criar tabela suppliers: column "none" does not exist
LINE 1: ...'Purchasing Manager', '49 Gilbert St.', 'London', None, 'EC1...
                                                             ^
HINT:  Perhaps you meant to reference the column "suppliers.phone".
[2025-01-30T04:32:05.256+0000] {logging_mixin.py:190} INFO - Table: territories -- parquetfile: /data/postgres/territories/2025-01-30/file.parquet
[2025-01-30T04:32:05.272+0000] {logging_mixin.py:190} INFO - Tabela territories não existe. Criando a tabela...
[2025-01-30T04:32:05.389+0000] {logging_mixin.py:190} INFO - Table: us_states -- parquetfile: /data/postgres/us_states/2025-01-30/file.parquet
[2025-01-30T04:32:05.404+0000] {logging_mixin.py:190} INFO - Tabela us_states não existe. Criando a tabela...
[2025-01-30T04:32:05.512+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-01-30T04:32:05.543+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T04:32:05.544+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etapa2_dag, task_id=copia, run_id=manual__2025-01-30T03:32:35.404173+00:00, execution_date=20250130T033235, start_date=20250130T043204, end_date=20250130T043205
[2025-01-30T04:32:05.557+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T04:32:05.558+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T04:32:05.558+0000] {logging_mixin.py:190} INFO - Dag name:etapa2_dag queued_at:2025-01-30 04:31:56.051873+00:00
[2025-01-30T04:32:05.559+0000] {logging_mixin.py:190} INFO - Task hostname:eed2ce10479b operator:PythonOperator
[2025-01-30T04:32:05.595+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T04:32:05.619+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-30T04:32:05.624+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
